server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: BoardGameCatalog
          uri: http://localhost:8081/
          predicates:
            - Path=/boardgames/**
        - id: ReviewServer
          uri: http://localhost:8082/
          predicates:
            - Path=/reviews/**